### ISSUE TITLE
画面共有時、参加者の書き込み機能が欲しい

### ISSUE THREAD

**Issue by d01tsumath** [iwate/VirtualOffice#14]
Slack 同様、画面共有時の書き込み機能があればよいなと思いました。

**Comment by iwate** [comment]
@d01tsumath 
デスクトップ共有をするユーザ(1人) ... a
デスクトップ共有を見るユーザ(N人) ... b

bの人たちだけでペン入れするのは簡単なのですが、aの人の画面（VSないしExcelないしPowerPoint、つまりはデスクトップ上のあらゆる画面）に描画するにはOSのAPI(例えばWin32API)に触る必要があるため、ブラウザからは実現できないです。

完全にSlackのようにアプリとして作るか、描画するだけのアプリを作成して配布する必要があります。

**Comment by d01tsumath** [comment]
なるほどー。
私としては[お絵かきの森](http://casual.hange.jp/oekaki/)をイメージとしてました。
これは Flash -> HTML5 に移行していたみたいなのでいけるかと思ってました。

**Comment by iwate** [comment]
お絵かきの森みたいな共有ホワイトボードならできるなあ。

でもホワイトボードだとo365のWhiteBoardがあるからそっちのほうができいいかも。

**Comment by iwate** [comment]
画面共有を見てる側：画面共有の動画上をマウスでぐりぐりすると手書きが可能です。書いた内容は共有されます。
画面共有をしてる側：他の参加者によってかかれたないようをスクリーン上に投影するには別途デスクトップアプリ（[screen drawer](https://github.com/iwate/screen-drawer)）を立ち上げる必要があります。
