### ISSUE TITLE
初期状態をマイクとカメラをOFFにしてほしい

### ISSUE THREAD

**Issue by hamamotsu** [iwate/VirtualOffice#2]
アクセスした際の初期状態がカメラとマイクが共にONなのでOFFにして欲しい。

**Comment by nabehiro** [comment]
自分の環境だと、カメラがうまく動作しない→マイクも動作しないになるのでいいかも

**Comment by iwate** [comment]
@nabehiro カメラやマイクのON/OFFはStreamのVideoTrack/AudioTrackのEnabledを操作します。

> 自分の環境だと、カメラがうまく動作しない→マイクも動作しないになるのでいいかも

この現象を回避するためにはStreamの生成時に手を加える必要があるので、この機能では解決できないかもです。

**Comment by iwate** [comment]
ひとまず、カメラだけOFFにしました。

**Comment by iwate** [comment]
いったんマイクOFFは保留
